Gitlab ci 1
Otus-DevOps-2018-05/lopvv_microservices pull request #4
Opened 2018-09-12 11:54 UTC by lopvv

# Выполнено ДЗ № 12

 - [x] Основное ДЗ
 - [ ] Задание со *

## В процессе сделано:
- Развернул Gitlab CI средствами GCE и docker
- Добавил код приложения в репозиторий
- Настроил pipeline

## Как запустить проект:
 docker-compose up -d

## Как проверить работоспособность:
- Зайти используя внешний адрес предоставленный GCP ‘http://<YOUR-VM-IP>' 

## PR checklist
 - [ ] Выставил label с номером домашнего задания
 - [x] Выставил label с темой домашнего задания

2018-11-01 09:32 UTC, WeitBelou commented on .gitlab-ci.yml
> +
Пропущен image

2018-11-01 09:32 UTC, grim-yawn requested changes

2018-11-01 09:32 UTC, WeitBelou commented on .gitlab-ci.yml
> +
Пропущен image

2018-11-10 17:40 UTC, lopvv commented on .gitlab-ci.yml
> +
Спасибо! добавил

2018-11-17 10:03 UTC, grim-yawn approved these changes

2018-11-17 12:03 UTC, merged